#+TITLE: 256k emacs 29.2 config (minimal)
#+AUTHOR: 256k

* CORE SETTINGS AND FUNCTIONS
** set backups directory
#+begin_src emacs-lisp
;; -*- lexical-binding: t; -*-
  (setq package-enable-at-startup t)
  (setq lexical-binding t)
  (setq backup-directory-alist '(("" . "~/.emacs.d/backup/")))
  (setq backup-by-copying t    ; Don't delink hardlinks
        delete-old-versions t  ; Clean up the backups
        version-control t      ; Use version numbers on backups,
        kept-new-versions 5    ; keep some new versions
        kept-old-versions 2)   ; and some old ones, too
  (setq use-package-always-ensure t)
  (setq auto-save-file-name-transforms
        `((".*" "~/.emacs.d/auto-save/" t)))

  (pending-delete-mode 1) ; when a piece of text is marked, typing will delete and replace that selection.
#+end_src


** setup package
#+begin_src emacs-lisp
  (require 'package)
  (setq package-archives
        '(("gnu-elpa" . "https://elpa.gnu.org/packages/")
          ("gnu-elpa-devel" . "https://elpa.gnu.org/devel/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")
          ("melpa" . "https://melpa.org/packages/")))

                                          ; Highest number gets priority (what is not mentioned has priority 0)
  (setq package-archive-priorities
        '(("gnu-elpa" . 3)
          ("melpa" . 2)
          ("nongnu" . 1)))
  (package-initialize)
#+end_src

** Disable Menubar, Toolbars and Scrollbars
#+begin_src emacs-lisp
  (menu-bar-mode 1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq frame-inhibit-implied-resize t) ; disables frame resizing when font resizing happens
  (setq inhibit-startup-screen 1)
  (electric-pair-mode 1)  ;; (){}""<>[]
  (context-menu-mode 1) ;; enables right click mouse menu

#+end_src

** toggle large font mode
#+begin_src emacs-lisp
  (defvar big-font-mode nil)
  (defun 256k/toggle-font-size ()
    "Toggle between two font sizes."
    (interactive)
    (if big-font-mode
        (progn
          (set-face-attribute 'default nil :height 180)
          (setq big-font-mode nil))
      (progn
        (set-face-attribute 'default nil :height 220)
        (setq big-font-mode t))))

#+end_src

** replace project grep with ripgrep
#+begin_src emacs-lisp
  (setq xref-search-program ;; Prefer ripgrep, then ugrep, and fall back to regular grep.
        (cond
         ((or (executable-find "ripgrep")
              (executable-find "rg"))
          'ripgrep)
         ((executable-find "ugrep")
          'ugrep)
         (t
          'grep)))
#+end_src

** Theme
#+begin_src emacs-lisp
      ;; (use-package doom-themes
      ;;   :ensure t
      ;;   :config
      ;;   (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
      ;;         doom-themes-enable-italic t) ; if nil, italics is universally disabled
      ;;   (doom-themes-visual-bell-config)
      ;;   (doom-themes-org-config))
      ;; (load-theme 'doom-one t)
    ;; (load-theme 'ef-spring t)
  (use-package anti-zenburn-theme
    :ensure t
    :config
    (load-theme 'anti-zenburn t))
#+end_src

** padding
#+begin_src emacs-lisp
  ;; (use-package spacious-padding
  ;;   :ensure t
  ;;   :config
  ;;   (setq spacious-padding-widths '(:internal-border-width 60 :right-divider-width 30 :scroll-bar-width 8))
  ;;         (spacious-padding-mode 1))
#+end_src

** define aliases
#+begin_src emacs-lisp
  (defalias 'list-buffers 'consult-buffer)
#+end_src

** Display Line Numbers and Truncated Lines
#+begin_src emacs-lisp
  (setq display-line-numbers-type t)
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)

  (global-visual-line-mode t) ;; wraps the text in a buffer
#+end_src

** Hide DIRED details
#+begin_src emacs-lisp
  (add-hook 'dired-mode-hook 'dired-hide-details-mode)
#+end_src
 
** Enabling shorthand block generation
#+begin_src emacs-lisp
  (require 'org-tempo)
  ;; allows the ability to generate #+begin blocks using `<s or q or e...etc
#+end_src

** Enabling Org Bullets
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (use-package org-bullets :ensure t)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

* PACKAGES
** norns
#+begin_src emacs-lisp
  (use-package norns
    :ensure t
    :bind
    (
     :map norns-mode-map
     ("C-c e b" . norns-load-current-script)
     ("C-c e r" . norns-send-selection)

     :map norns-maiden-repl-mode-map
     ("C-c e b" . norns-rerun)

     :map norns-sc-repl-mode-map
     ("C-." . norns-sc-stop))
    )
#+end_src

** rainbow delimiters
#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :hook
    (prog-mode . rainbow-delimiters-mode))

#+end_src

** evil
#+begin_src emacs-lisp
  ;; (use-package evil 
  ;;   :ensure t
  ;;   :init
  ;;   (setq evil-undo-system 'undo-redo)
  ;;   (setq evil-disable-insert-state-bindings t)
  ;;   (setq evil-want-C-u-scroll t)
  ;;   :config
  ;;   (evil-mode))
#+end_src

** try
#+begin_src emacs-lisp
  (use-package try :ensure t :defer t)
#+end_src

** which key
#+begin_src emacs-lisp
  ;; M-x customize-group is a way to find all the variables associated with a package.
  (use-package which-key
      :ensure t
      :config
      (setq which-key-max-display-columns 2)
      ;; (setq which-key-min-column-description-width 0.001)
      ;; (setq which-key-separator ":")
      (which-key-mode t))
#+end_src

** consult
#+begin_src emacs-lisp
  (use-package consult
    :ensure t)

#+end_src

** magit
#+begin_src emacs-lisp
  (use-package magit :ensure t)
#+end_src

** git gutter
#+begin_src emacs-lisp
  (use-package git-gutter
    ;; adds markings for file changes
    :ensure t
    :config
    (global-git-gutter-mode +1))
#+end_src
  
** expand region
#+begin_src emacs-lisp
  (use-package expand-region
    :ensure t
    :bind ("C-=" . er/expand-region))
#+end_src
  
** exec path from shell
#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :ensure t
    :config
    (exec-path-from-shell-initialize))
#+end_src
  
** vertico
#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (vertico-mode)
    (vertico-multiform-mode)
    :config
    (setq vertico-multiform-commands
          '((consult-buffer grid))))
  ;; vertico-multiform-commands lets you set different display modes for different commands.
#+end_src

** treemacs
#+begin_src emacs-lisp
  (use-package treemacs
    :ensure t
  :bind
  ("C-c b" . treemacs)
    :config
    (treemacs-follow-mode t)
    (treemacs-project-follow-mode t))
#+end_src

** company
#+begin_src emacs-lisp
  (use-package company
    :ensure t
    :bind ("C-." . company-complete)
    :init
    (setq company-minimum-prefix-length 1)
    (add-hook 'after-init-hook 'global-company-mode))
#+end_src


** marginalia
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :config
    (marginalia-mode))
#+end_src

** embark
#+begin_src emacs-lisp
  (use-package embark
    :ensure t
    :after
    (use-package embark-consult
      :ensure t))
#+end_src

** slime
#+begin_src emacs-lisp
  (use-package slime
    :ensure t
    :init
    (setq inferior-lisp-program "sbcl"))
#+end_src

* Languages and linting
** flycheck eglot
#+begin_src emacs-lisp
  (use-package flycheck-eglot
    :ensure t
    :config
    (global-flycheck-eglot-mode 1))

#+end_src

** Language modes
#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/site-lisp")

  (use-package forth-mode
    :ensure t)

  (use-package lua-mode 
    :ensure t)
#+end_src

** vuejs
#+begin_src emacs-lisp
  (add-to-list 'load-path (concat user-emacs-directory "vue-ts-mode"))
(require 'vue-ts-mode)
#+end_src
** treesit
#+begin_src emacs-lisp
  (use-package treesit-auto
    :custom
    (treesit-auto-install 'prompt)
    :config
    (treesit-auto-add-to-auto-mode-alist 'all)
    (global-treesit-auto-mode))

  (setq treesit-font-lock-level 4)
  (add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.js\\'" . typescript-ts-mode))
  (add-to-list 'auto-mode-alist '("\\.c\\'" . c-ts-mode))
#+end_src

* LSP
#+begin_src emacs-lisp
  ;; LSP-mode solution

  ;; (use-package lsp-mode
  ;;   :ensure t
  ;;   :init
  ;;   ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  ;;   (setq lsp-keymap-prefix "C-c l")
  ;;   :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
  ;;          (typescript-ts-mode . lsp-deferred)
  ;;          (tsx-ts-mode . lsp-deferred))
  ;;   :commands lsp)

  ;; (use-package lsp-ui
  ;;   :ensure t
  ;;   :commands lsp-ui-mode)
  ;; (with-eval-after-load 'lsp-mode
  ;;   (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration))
  ;; (fset #'jsonrpc--log-event #'ignore) ;; helps remove laggy typing
  ;; (use-package consult-lsp
  ;;   :ensure t)


  ;; ;; =========================

  ;; eglot solution

  (require 'jsonrpc)
  (require 'eglot)

  (use-package eglot
    :hook (prog-mode . eglot-ensure)
    :config
    (fset #'jsonrpc--log-event #'ignore))

  (setq read-process-output-max (* 1024 1024))

#+end_src

** prettier setup
#+begin_src emacs-lisp
  (use-package prettier
            :ensure t :defer t)
#+end_src

** Claude performance increase tips:
#+begin_src emacs-lisp
  ;; tips from claude
  ;; add :defer t to packages that don't run from the start to improve startup

  (setq gc-cons-threshold (* 100 1000 1000))
  ;; GC when idle for 5 seconds
  (run-with-idle-timer 5 t #'garbage-collect)

#+end_src


*** read-process-output-max controls how much data Emacs reads from an external process in a single chunk.
When Emacs communicates with external processes (like language servers, shell commands, etc.), it reads their output in chunks.
The default value is quite small - only 4096 bytes (4KB).
Language servers like TypeScript's tsserver can send large JSON responses - think IntelliSense results with hundreds of completions, or diagnostics for your whole project. If Emacs can only read 4KB at a time, it has to make many small reads, which is inefficient.
